import Head from 'next/head';
import { NextPage } from 'next';
import Home from '../screens/home';

const HomePage: NextPage = () => {
	return (
		<>
			<Head>
				<title>Hi Jobs</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Home />
		</>
	);
};

export default HomePage;
